services:
  caldera:
    image: mitre/caldera:latest
    container_name: caldera
    ports:
      - "8888:8888"
    volumes:
        - ./conf:/caldera/conf
        - ./caldera-data:/usr/src/app/data
    restart: unless-stopped

